packages:
  - template/base
  - template/config/**
  - template/formattin/**
  - template/linting/**
  - template/tsconfig/**

ignoredBuiltDependencies:
  - '@nightwatch/nightwatch-inspector'
  - chromedriver
  - cypress
  - esbuild
  - geckodriver
