packages:
  - template/base
  - template/config/**
  - template/formatting/**
  - template/linting/**
  - template/tsconfig/**

allowBuilds:
  cypress: false
  esbuild: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 5.0.0
  vite-plus: latest
dedupePeers: true
overrides:
  '@vitest/browser': 5.0.0
  '@vitest/browser-preview': 5.0.0
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
