packages:
  - template/base
  - template/config/**
  - template/formatting/**
  - template/linting/**
  - template/tsconfig/**

allowBuilds:
  cypress: false
  esbuild: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10
  vite-plus: latest
dedupePeers: true
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
