packages:
  - template/base
  - template/config/**
  - template/formatting/**
  - template/linting/**
  - template/tsconfig/**

allowBuilds:
  cypress: false
  esbuild: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 5.0.1
  vite-plus: latest
dedupePeers: true
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-darwin-arm64@1.0.0'
  - '@voidzero-dev/vite-plus-darwin-x64@1.0.0'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0'
  - '@voidzero-dev/vite-plus-linux-x64-musl@1.0.0'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0'
  - vite-plus@1.0.0
  - '@voidzero-dev/vite-plus-core@1.0.0'
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
