name: Publish

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'vuejs/create-vue'
    # Use Publish environment for deployment protection
    environment: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm publish --no-git-checks
